stages:
    - test

test:
    stage: test
    script:
        - echo "Testing"
        - pwd
        - whoami
        - python3 --version
        - python3 -m pip install scipy
        - python3 -m unittest discover
    tags:
        - sh_test
