image: oberbichler/ubuntu-dev

stages:
    - test

test:
    stage: test
    script:
        - echo "Testing"
        - pwd
        - python3 --version
        - python3 -m unittest discover
    tags:
        - test
