image: gitlab.lrz.de:5005/gu42dib/test_ci:latest

stages:
    - test

test:
    stage: test
    script:
        - echo "Testing"
        - pwd
        - gcc --version
        - python3 --version
        - python3 -m unittest discover
    tags:
        - test
